FROM reg.aichallenge.ir/python:3.10
RUN dpkg --add-architecture i386
RUN apt-get update && apt install -y vim curl gettext unrar-free libc6-i386 libc6-x32 libasound2 \
    libxi6 libxtst6 libxslt-dev libffi-dev libssl-dev python3.9-dev
ADD ./java /tmp
RUN cd /tmp && \
 unrar Java_SE_Development_Kit_18.0.2_Linux_Debian_x64_Downloadly.ir.rar && \
 cd "Java SE Development Kit 18.0.2 Linux Debian x64" && \
 dpkg -i jdk-18_linux-x64_bin_Downloadly.ir.deb

